CC:=clang -target i386-pc-none-gnu -D__LLVM__
CXX:=clang++ -target i386-pc-none-gnu -D__LLVM__
LD:=i686-elf-ld
LDFLAGS:= \
	--sysroot=$(SYSROOT)
AR:=i686-elf-ar
ARFLAGS:=rcs
AS=nasm
ASFLAGS=-f elf32
STRIP:=i686-elf-strip
