CONFIGS = \
	CONFIG \
	CONFIG_ARCH \
	CONFIG_COMPILER \
	CONFIG_BUILD_DIRECTORY \
	CONFIG_VMACHINE \
	CONFIG_LOADER \
	CONFIG_LOG \
	CONFIG_MEMORY \
	CONFIG_NAME \
	CONFIG_VERSION \
	CONFIG_IS_RELEASE

CONFIGS_PASS_TO_COMPILER = \
	CONFIG \
	CONFIG_ARCH \
	CONFIG_TOOLCHAIN \
	CONFIG_NAME \
	CONFIG_VERSION \
	CONFIG_IS_RELEASE

CONFIG?=debug

include make/user.mk
include make/$(CONFIG).mk

CONFIG_ARCH?=x86_32

CONFIG_TOOLCHAIN?=gnu

CONFIG_BUILD_DIRECTORY?=$(shell pwd)/build

CONFIG_VMACHINE?=qemu

CONFIG_LOADER?=grub

CONFIG_LOG?=true

CONFIG_STRIP?=false

CONFIG_MEMORY?=256

CONFIG_NAME?=hegel

CONFIG_VERSION?=$(shell date +'%y.%W')

define BUILD_CONFIG_TEMPLATE =
-D__$(1)__=$(if $(filter $($(1)),true),1,$(if $(filter false, $($(1))),0,\""$($(1))"\"))
endef

BUILD_CONFIGS := $(foreach cfg, $(CONFIGS_PASS_TO_COMPILER), $(call BUILD_CONFIG_TEMPLATE,$(cfg)))

print-config:
	@echo $(BUILD_CONFIGS)
